// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWFdlcB_nYS7RtQb_fjQ2kubcqPO89KMA',
    appId: '1:398034483393:web:d201b3520b241296873c40',
    messagingSenderId: '398034483393',
    projectId: 'hayvandostu-b4ce3',
    authDomain: 'hayvandostu-b4ce3.firebaseapp.com',
    storageBucket: 'hayvandostu-b4ce3.appspot.com',
    measurementId: 'G-GMKBRQ00LE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMRjz-SQYI5Mt5fBFfhfgkp3jLR4oU2vY',
    appId: '1:398034483393:android:8734f0136e72d854873c40',
    messagingSenderId: '398034483393',
    projectId: 'hayvandostu-b4ce3',
    storageBucket: 'hayvandostu-b4ce3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy5YsKEhGi7HTlbHztR14miAQgRL0dQjE',
    appId: '1:398034483393:ios:1febeecc2aaca46b873c40',
    messagingSenderId: '398034483393',
    projectId: 'hayvandostu-b4ce3',
    storageBucket: 'hayvandostu-b4ce3.appspot.com',
    iosClientId: '398034483393-n6pcmojaaderl7f0ksorll8qipvm7t39.apps.googleusercontent.com',
    iosBundleId: 'com.example.hayvanDostu',
  );
}
